---
# -----------------------------------------------------------------------------
# Ansible Galaxy Requirements
# -----------------------------------------------------------------------------
# Install: ansible-galaxy install -r requirements.yml
# -----------------------------------------------------------------------------

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: cloud.terraform
    version: ">=1.1.0"
