---
# =============================================================================
# HAProxy Role - Handlers
# =============================================================================

- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
